name: verify

on: push

jobs:
  steps:
  - name: Git checkout
    uses: actions/checkout@v3
    with:
      path: main
      fetch-depth: 0

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: 3.12.0

  - name: Install oj-verify
    run: pip3 install -U online-judge-verify-helper

  - name: Clone AC-Library
    uses: actions/checkout@v3
    with:
      repository: atcoder/ac-library
      path: ac-library
      sparse-checkout: atcoder

  - name: Run tests
    env:
      CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
    run: oj-verify all